# Generated by Django 4.2.5 on 2024-02-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
