# Generated by Django 4.2.5 on 2024-02-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0005_aircraft_airport_booking_flight_promotion_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='booking',
        ),
        migrations.AddField(
            model_name='feedback',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.flight'),
        ),
    ]
