# Generated by Django 4.2.5 on 2024-02-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0006_remove_feedback_booking_feedback_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Premium Economy', 'Premium Economy'), ('Business', 'Business')], default='Economy', max_length=50),
        ),
    ]
