# Generated by Django 4.2.5 on 2024-02-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0007_booking_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_type',
            new_name='seat_type',
        ),
    ]
