# Generated by Django 4.2.5 on 2024-02-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0008_rename_user_type_booking_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.user', unique=True),
        ),
    ]
