# Generated by Django 4.2.5 on 2024-02-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0011_flight_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
    ]
