# Generated by Django 4.2.5 on 2024-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0012_remove_flight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
