# Generated by Django 4.2.5 on 2024-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0013_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='amount_business',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='amount_economy',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='amount_premium',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
