# Generated by Django 4.2.5 on 2024-02-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0014_flight_amount_business_flight_amount_economy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='amount_business',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='amount_economy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='amount_premium',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
